/*Index's*/

--CREATE INDEX idx_idCinemaOnSALA ON PROJ_CINEMAS.SALACINEMA(id_cinemaSALACINEMA);

--CREATE INDEX idx_idSalaOnSESSAO ON PROJ_CINEMAS.SESSAO(id_salaSESSAO);

--CREATE INDEX idx_idFilmeOnSESSAO ON PROJ_CINEMAS.SESSAO(id_filmeSESSAO);