CREATE SCHEMA PROJ_CINEMAS;
GO

CREATE TABLE PROJ_CINEMAS.UTILIZADOR(
	id			int,
	email		nvarchar(50),	
	pw			nvarchar(50),
	username	nvarchar(50),
	
	CONSTRAINT PK_UTILIZADOR PRIMARY KEY(id)
)

--Ver a parte da password do utilizador
DROP TABLE PROJ_CINEMAS.UTILIZADOR;

INSERT INTO PROJ_CINEMAS.UTILIZADOR VALUES (4, 'rogerio@gmail.com', 'r12345', 'rogerio10');
INSERT INTO PROJ_CINEMAS.UTILIZADOR VALUES (16, 'tomas@gmail.com', 't6969', 'tomas7');
INSERT INTO PROJ_CINEMAS.UTILIZADOR VALUES (54, 'joao@gmail.com', 'joao2004', 'jonhy7');
INSERT INTO PROJ_CINEMAS.UTILIZADOR VALUES (21, 'mariana@gmail.com', 'mary2001', 'mariana1');
INSERT INTO PROJ_CINEMAS.UTILIZADOR VALUES (69, 'nuno@gmail.com', 'nunoST', 'NunoAd');
INSERT INTO PROJ_CINEMAS.UTILIZADOR VALUES (41, 'pedro10@gmail.com', 'pedroTavares', 'Pedro14');


CREATE TABLE PROJ_CINEMAS.CLIENTE(
	id_cliente		int,
	idade			int,	
	num_CC			int,
	telefone		int,
	
	CONSTRAINT PK_CLIENTE PRIMARY KEY(id_cliente),
	CONSTRAINT FK_CLIENTE FOREIGN KEY(id_cliente) REFERENCES PROJ_CINEMAS.UTILIZADOR(id)
)

INSERT INTO PROJ_CINEMAS.CLIENTE VALUES (4, 53, 30467844, 925888833);
INSERT INTO PROJ_CINEMAS.CLIENTE VALUES (16, 17, 30777844, 925439120);
INSERT INTO PROJ_CINEMAS.CLIENTE VALUES (54, 21, 20555864, 935444433);
INSERT INTO PROJ_CINEMAS.CLIENTE VALUES (21, 26, 20400324, 926376109);


CREATE TABLE PROJ_CINEMAS.ADMINISTRADOR(
	id_admin			int,
	num_funcionario		int,	
	id_cinema			int,
	
	CONSTRAINT PK_ADMINISTRADOR PRIMARY KEY(id_admin),
	CONSTRAINT FK1_ADMINISTRADOR FOREIGN KEY(id_admin) REFERENCES PROJ_CINEMAS.UTILIZADOR(id),
	CONSTRAINT FK2_ADMINISTRADOR FOREIGN KEY(id_cinema) REFERENCES PROJ_CINEMAS.CINEMA(id)
)

INSERT INTO PROJ_CINEMAS.ADMINISTRADOR VALUES (69, 202041, 410);
INSERT INTO PROJ_CINEMAS.ADMINISTRADOR VALUES (41, 101030, 130);

CREATE TABLE PROJ_CINEMAS.CINEMA(
	id		int,
	nome	nvarchar(50),	
	
	CONSTRAINT PK_CINEMA PRIMARY KEY(id),
)

INSERT INTO PROJ_CINEMAS.CINEMA VALUES (410, 'Cinemas NOS Palácio do Gelo');
INSERT INTO PROJ_CINEMAS.CINEMA VALUES (206, 'Cinemas NOS Forum Viseu');
INSERT INTO PROJ_CINEMAS.CINEMA VALUES (130, 'Cinemas NOS Oeiras Parque');
INSERT INTO PROJ_CINEMAS.CINEMA VALUES (314, 'Cinemas NOS Norte Shopping');
INSERT INTO PROJ_CINEMAS.CINEMA VALUES (360, 'Cinemas NOS Arrábida Shopping');
INSERT INTO PROJ_CINEMAS.CINEMA VALUES (387, 'Cinemas NOS Mar Shopping');


