USE P1G9;
GO

CREATE SCHEMA STOCK_MANAGEMENT;
GO

CREATE TABLE STOCK_MANAGEMENT.PRODUTO(
	codigo			int,
	preco_unidades	int,
	nome			NVARCHAR(30),
	taxa_iva		int,

	CONSTRAINT PK_PRODUTO PRIMARY KEY(codigo)
);

CREATE TABLE STOCK_MANAGEMENT.TEM_EP(
	codigo_produto		int,
	numero_encomenda	int,
	quantidade			int,

	CONSTRAINT PKS_TEM_EP PRIMARY KEY(codigo_produto,numero_encomenda),
	CONSTRAINT FK1_TEM_EP FOREIGN KEY(codigo_produto) REFERENCES STOCK_MANAGEMENT.PRODUTO(codigo),
	CONSTRAINT FK2_TEM_EP FOREIGN KEY(numero_encomenda) REFERENCES STOCK_MANAGEMENT.ENCOMENDA(numero),
);

CREATE TABLE STOCK_MANAGEMENT.ENCOMENDA(
	numero			int,
	encomenda_data	date,
	NIF_fornecedor	int,

	CONSTRAINT PK_ENCOMENDA PRIMARY KEY(numero),
	CONSTRAINT FK_ENCOMENDA FOREIGN KEY(NIF_fornecedor) REFERENCES STOCK_MANAGEMENT.FORNECEDOR(NIF)
);

CREATE TABLE STOCK_MANAGEMENT.FORNECEDOR(
	NIF						int,
	endereco				NVARCHAR(100),
	codigo_pagamento		int,
	nome					NVARCHAR(30),
	numero_FAX				int,
	codigo_TipoFornecedor	int,

	CONSTRAINT PK_FORNECEDOR PRIMARY KEY(NIF),
	CONSTRAINT FK_FORNCEDOR FOREIGN KEY(codigo_TipoFornecedor) REFERENCES STOCK_MANAGEMENT.TIPO_FORNECEDOR(codigo)
);

CREATE TABLE STOCK_MANAGEMENT.TIPO_FORNECEDOR(
	codigo		int,
	designacao	NVARCHAR(1000),

	CONSTRAINT PK_TIPO_FORNECEDOR PRIMARY KEY(codigo)
);